# Generated by Django 5.2.1 on 2025-05-31 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campanha',
            options={'verbose_name': 'Campanha', 'verbose_name_plural': 'Campanhas'},
        ),
        migrations.AlterModelOptions(
            name='cidadao',
            options={'verbose_name': 'Cidadão', 'verbose_name_plural': 'Cidadãos'},
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='mapa',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name': 'Organização', 'verbose_name_plural': 'Organizações'},
        ),
        migrations.AlterModelOptions(
            name='pesquisador',
            options={'verbose_name': 'Pesquisador', 'verbose_name_plural': 'Pesquisadores'},
        ),
        migrations.AlterModelOptions(
            name='tubarao',
            options={'verbose_name': 'Tubarão', 'verbose_name_plural': 'Tubarões'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
